### ISSUE TITLE
The mask amount isn;t updated

### ISSUE THREAD

**Issue by chi227** [tnstiger/mask-gdg#7]
https://mask.goodideas-studio.com/

The data date is still on 2020-02-07 00:38:34 更新.
After refresh the page, there are still old data.
![image](https://user-images.githubusercontent.com/15961744/74010877-780f3600-49c1-11ea-92ee-1e6520b77f12.png)

**Comment by cage1016** [comment]
資料未更新己經解決.

**Comment by chgc** [comment]
資料更新時間已修正
